version: '3.1'

services:
  postgresql-cadastro:
    image: postgres:15-alpine
    container_name: postgres-cadastro
    environment:
      POSTGRES_DB: vinho-notas-cadastro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567
    ports:
      - "5432:5432"
    volumes:
      - ./.data/postgresql/data-cadastro:/var/lib/postgresql/data
    networks:
      - main-network

  postgresql-vinho:
    image: postgres:15-alpine
    container_name: postgres-vinho
    environment:
      POSTGRES_DB: vinho-notas-vinho
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567
    ports:
      - "5433:5432"
    volumes:
      - ./.data/postgresql/data-vinho:/var/lib/postgresql/data
    networks:
      - main-network

  postgresql-avaliacao:
    image: postgres:15-alpine
    container_name: postgres-avaliacao
    environment:
      POSTGRES_DB: vinho-notas-avaliacao
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567
    ports:
      - "5434:5432"
    volumes:
      - ./.data/postgresql/data-avaliacao:/var/lib/postgresql/data
    networks:
      - main-network

  postgresql-sonar:
    image: postgres:15-alpine
    container_name: postgres-sonar
    environment:
      POSTGRES_DB: vinho-notas-sonar
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567
    ports:
      - "5435:5432"
    volumes:
      - ./.data/postgresql/data-sonar:/var/lib/postgresql/data
    networks:
      - main-network

networks:
  main-network:
    driver: bridge
