CREATE SCHEMA IF NOT EXISTS degustacao;

CREATE TABLE degustacao.tbtastingcard (
    id uuid NOT NULL UNIQUE,
    winetasted varchar(255) NULL,
    tastingdata date NULL,
    tastingtype varchar(255) NULL,
    harvest varchar(255) NULL,
    grapes varchar(255) NULL,
    country varchar(255) NULL,
    region varchar(255) NULL,
    clarity varchar(255) NULL,
    brightness varchar(255) NULL,
    viscosity varchar(255) NULL,
    colorred varchar(255) NULL,
    colorwhite varchar(255) NULL,
    colorrose varchar(255) NULL,
    visual_inspection_classification varchar(255) NULL,
    intensity varchar(255) NULL,
    olfactory_inspection_persistence varchar(255) NULL,
    quality varchar(255) NULL,
    fruity varchar(255) NULL,
    dryfruits varchar(255) NULL,
    florals varchar(255) NULL,
    vegetablesandherbs varchar(255) NULL,
    minerals varchar(255) NULL,
    spices varchar(255) NULL,
    animals varchar(255) NULL,
    empireumatics varchar(255) NULL,
    wood varchar(255) NULL,
    chemicals varchar(255) NULL,
    lacteal varchar(255) NULL,
    sweets varchar(255) NULL,
    olfactory_inspection_classification varchar(255) NULL,
    body varchar(255) NULL,
    sweetness varchar(255) NULL,
    tannin varchar(255) NULL,
    acidity varchar NULL,
    alcohol varchar NULL,
    gustatory_inspection_persistence varchar NULL,
    maturity varchar NULL,
    typicality varchar NULL,
    gustatory_inspection_classification varchar(255) NULL,
    generalopinion varchar(500) NULL,
    pointscale varchar(255) NULL,
    dthreg timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    userreg varchar(30) NULL,
    dthalt timestamp NULL,
    useralt varchar(30) NULL,
    PRIMARY KEY (id)
);


