ALTER TABLE cadastro.tbcountry ADD COLUMN dthreg TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE cadastro.tbcountry ADD COLUMN userreg VARCHAR(30) NULL;
ALTER TABLE cadastro.tbcountry ADD COLUMN dthalt TIMESTAMP NULL;
ALTER TABLE cadastro.tbcountry ADD COLUMN useralt VARCHAR(30) NULL ;