ALTER TABLE cadastro.tbperson ADD COLUMN dthreg TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE cadastro.tbperson ADD COLUMN userreg VARCHAR(30) NULL;
ALTER TABLE cadastro.tbperson ADD COLUMN dthalt TIMESTAMP NULL;
ALTER TABLE cadastro.tbperson ADD COLUMN useralt VARCHAR(30) NULL ;
