server:
  error:
    include-stacktrace: never
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/vinho-notas-avaliacao
    username: postgres
    password: 1234567

  jpa:
    hibernate:
      ddl-auto: update
      default_schema: avaliacao
    show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
springdoc:
  api-docs:
    path: /api-docs
