server:
  error:
    include-stacktrace: never
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/vinho-notas-degustacao
#    url: jdbc:postgresql://postgresql-degustacao:5432/vinho-notas-degustacao
    username: postgres
    password: 1234567

  jpa:
    hibernate:
      ddl-auto: update
      default_schema: degustacao
    show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
springdoc:
  api-docs:
    path: /api-docs

